<!DOCTYPE html>
<html lang="cs-cz">
        <head>
            <base href="http://bergul.xf.cz/php/" />
                <meta charset="UTF-8" />
                <title><?= $title ?></title>
                <meta name="description" content="<?= $description ?>" />
                <meta name="keywords" content="<?= $keywoards ?>" />
                <link rel="stylesheet" href="style.css" type="text/css"/>
        </head>

        <body>
                <header>
                        <h1>Picture sharing test</h1>
                </header>

                <nav>
                        <ul>
                                <li><a href="uvod">Home</a></li>
                                <li><a href="clanek">Články</a></li>
                                <li><a href="login">Login</a></li>
                        </ul>
                </nav>
                <br clear="both" />

                <article>
                    <?php $this->controller->showView(); // vložení aktuálního pohledu do šablony ?>
                </article>

                <footer>
                        <p>Creating from tutorial by
                        <a href="http://www.itnetwork.cz" target="_blank">itnetwork.cz</a>.</p>
                </footer>
        </body>
</html>